# -*- coding: utf-8 -*-
"""test_script_long.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyxsjHT-FzXRsZZ1U7B2HtoFnvPVJ7Be

# Test script that saves a dataframe to a VM permanent disk
"""

import pandas as pd
import time
import os

# print current wd
print(os.getcwd())

df_result = pd.DataFrame({'iteration': [], 'status': []})

for i in range(60):
  # append current result
  df_cur_result = pd.DataFrame({'iteration': [i], 'status': ['done']})
  df_result = pd.concat([df_result, df_cur_result], ignore_index=True, axis=0)
  time.sleep(1) # wait 1 second
  # optional print statement to show progress and facilitate debugging
  if i % 10 == 0: # use modulo here to print only every 10 iterations
    print('Finished iteration ' + str(i))

# save to current working directory
df_result.to_csv('df_result_long.csv')